language: go
go:
  - stable
env:
  - GO111MODULE=on
script:
  - rm go.sum # Workaround for https://github.com/kubernetes/kubernetes/issues/69040
  - node --version
  - nvm install 11
  - nvm use 11
  - node --version
  - make all
# Use different deploy prep based on OS
matrix:
  include:
    - os: linux
      before_deploy:
        - sudo apt-get install -y upx
        - make dist-release
        # TODO: make docker && docker push
    - os: osx
      before_deploy:
        - make bottle
        # TODO: Deploy step pushes bottle
      after_deploy:
        # TODO: push new bottle commit to lyraproj/homebrew-lyra
deploy:
  provider: releases
  api_key:
    secure: xgSvTz8VRXtl7DhZzmG0HkLJjD3zEWFkvii43NeTs/r76lSwPZzMJL3+h+PK5mUMX8hx1mzozPwiwecpdNf7pIRLIbIc4e3e8Pqu6b1X5HRNiDfKO/d1IiUEcV33X/F5i8Gwcbz13MPdiB5KJ2zjW8h+ApsuPJqUKNuNaeBv4irZW9GPBNxU592ND3ht1ZvA1q/XSZHGjv3JNbVYDm6SF+29kL5VyaYhh8DD7eEvaXBQNlxK3qjHWSqe5JfpwuHY1XU3JDuSLD3OG+ZrMrQHxECq76DWVfqKTWMvW/NTkLjGyOKjWdOfBszc9FRDn2UzjB5hzt5sD1k+X5P3OWv5a7jx47xCcJi5jrIQa+96n0uwf0HtIC8dbDaWaVB5CWsQne+3ImWs4bbFNrXmZjBBQ4qwXPoVYzCxDcOkRk37ZUid6qE7qNMjUJdtl18rVN5RhKVnxuFuc2C1WoEXs1wAKOYEt7UP1R1If7qo0DexKkcPTP/qKy69Kt2wx3X27nF8AjpA3NJUfc6XDZWltud7RIfSA8+878ekgCditRh4Ph0c3fSuQHge3PYlpzmk5U4Cd3Ol+Ow/Rgktt4YGuv2ZqMx3LaYAUF0nxNdHPhc1OVi/9hb3+oopj7Detzugv1ExG0skBMHISENncpTe+DdpOtEpsu5g64DpZJ4PtMDWSlg=
  file_glob: true
  file: build/*.tar.gz*
  skip_cleanup: true
  on:
    repo: lyraproj/lyra
    tags: true
notifications:
  slack:
    secure: t03TPD1KQogKliNQ9yB1HGLIUcIiLIjsY/PVCkILBMXCXNuO28Yd9S+T4KkvNHds+HvzLTMVqN03/vdqubhtJb4HLmv5Wib18lRao3MOkeZEVbs3qGoEjgpWELJHIrF22bBxPm4tvGM8NDGHV2bgZuGszu7peEGRaJ8IhhpHlA1T3jgmfKCaJxvvxYxn0tPOLVGBdisDZT9JsfXEdf8CeiiyipwWq07w0M48BbqbqPUhfPlL325+SmDgkM+NY+FhMagqcme+F0JaosvAqvotLO/PzhyguCrm5q6hC7gnkIeJaYrPJeWLrIPABhtc62WR7fBkmTrrqSwppKcHSiwuiDsXbEBemxN5BsDE1r6L3DJvyCuhdwBVMjmT2ZZx0ABnf3TBBVmYEhuk4yORU1SS81SSv+PvouOaiHylIWV4Dw0tx7gMakcnZkGmLVt3pKXWuwwPMJG1LKPq4aNR0YgZ2xeBeaKBbxPlAeB3Awp9vJlkAz8egXk98IN6vMZaO26nIwUcMD81tRZe9WWSUk5f5epHG0A4w5BE9Jg2xFuvghNo2CY65cg3V3AsNgkzdNS7THGlgKZWvK4pyIbSQF8HBf3c4VHF0xB7F9Bm/zPTbu2u2uetjOJWI+06HQ48e00hgbfNc1YTo3lsb3mx3RDawGgwkZCR3ovaDjJNTbI59Xc=
branches:
  except:
    - /(ux.+|ux)/
cache:
  directories:
    - $GOPATH/pkg/mod/
    - $HOME/.cache/go-build/
